# sensible defaults please ğŸ™ - would love to be able to just use the svc 
# address so this doesn't need configuring when running in same ns
model_endpoint: <MODEL_ENDPOINT>
input_node: input
model_name: jukebox
search_as_default: false

# naming convention for images should take the form 
# SCENARIO-VERSION 
# simple-1.0
# transformer-1.2
# feast-1.1
# latest - points to , well you guessed it, latest :P
image: quay.io/rhoai-mlops/jukebox-ui:latest